version: "3.8"

# Repository for the image below: https://github.com/itzg/docker-minecraft-server

services:
  minecraft:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      JVM_OPTS: -XX:MaxMetaspaceSize=512M -Dfml.queryResult=confirm -Dterminal.jline=false -Dterminal.ansi=true -XX:+UseContainerSupport -XX:+UseG1GC -XX:MaxGCPauseMillis=130 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=28 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=3 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150 -Dlog4j.configurationFile=log4j2_112-116.xml
      USE_AIKAR_FLAGS: true
      EULA: true
      TYPE: AUTO_CURSEFORGE
      CF_SLUG: gregtech-expert-2
      # Get the ID of the Server version from CF. The following is an example and specifies v2.6.7
      # https://www.curseforge.com/minecraft/modpacks/gregtech-expert-2/files
      CF_FILE_ID: 5613389
      # Default RAM allocation
      MEMORY: 4G
      OPS: Steve
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
    tty: true
    stdin_open: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
